### PR TITLE
Updating to dragonfly v0.9.6 (master)

### PR DESCRIPTION
**Pull request by lightyisreal**

### CODE REVIEW

**Comment by andreashgk** [comment]
Did you run `go fmt ./...` on this? The formatting seems off

**Comment by lightyisreal** [comment]
Git did very weird things while I was trying to commit this

**Comment by andreashgk** [comment]
formatting still looks incorrect

**Comment by andreashgk** [comment]
My apologies, I was incorrect. It seems like the default formatting has changed since i last used it. I will be closing this PR now as there was a PR for the latest stable version

**Pull request closed without merging**
